/* Demo Data for Ghost Guardian */

export const demoVideos = [
  {
    id: "v1",
    title: "Is Consciousness Fundamental? — The Long Signal, Ep. 148",
    publishedAt: "2026-08-24T14:00:00.000Z",
    views: 184320,
    likes: 12450,
    commentCount: 847,
    duration: "1:12:34",
    transcriptExcerpt:
      "Around the 42-minute mark we argue that if experience is fundamental, then physics describes the behaviour of experience rather than replacing it. That's not mysticism — it's a claim about where explanation bottoms out.",
    notes: "Kept the panpsychism section deliberately short; a follow-up is planned.",
  },
  {
    id: "v2",
    title: "I Gave My AI a Face (And It Went Weird) — Ep. 147",
    publishedAt: "2026-08-17T14:00:00.000Z",
    views: 96540,
    likes: 8200,
    commentCount: 620,
    duration: "58:22",
    transcriptExcerpt:
      "The avatar was designed to be relatable rather than impressive. Yes, that includes the hairline. The point is that people talk differently to a face than to a text box.",
    notes: "High engagement on the humorous design choice.",
  },
  {
    id: "v3",
    title: "What LLMs Actually Do — Ep. 145",
    publishedAt: "2026-08-03T14:00:00.000Z",
    views: 240110,
    likes: 19800,
    commentCount: 1540,
    duration: "1:05:18",
    transcriptExcerpt:
      "Next-token prediction is the training objective, not a complete description of the learned model. Whether prediction can constitute understanding is the open question, and we don't resolve it here.",
    notes: "Technical philosophical deep dive on Searle & semantics.",
  },
];

export const demoCommenters = [
  {
    id: "c1",
    handle: "@marisol.reads",
    displayName: "Marisol",
    firstSeen: "2024-03-11T00:00:00.000Z",
    interactions: 96,
    episodesParticipated: 47,
    category: "returning",
    tags: ["Returning member", "Thoughtful contributor"],
    note: "Previously discussed her own AI companion project (Ep. 121).",
  },
  {
    id: "c2",
    handle: "@devon_k",
    displayName: "Devon K.",
    firstSeen: "2025-06-02T00:00:00.000Z",
    interactions: 21,
    episodesParticipated: 12,
    category: "frequent",
    tags: ["Frequent contributor", "Asks good questions"],
    note: "Consistently asks grounded technical questions on philosophy of mind.",
  },
  {
    id: "c3",
    handle: "@quietpine",
    displayName: "quietpine",
    firstSeen: "2026-08-20T00:00:00.000Z",
    interactions: 2,
    episodesParticipated: 1,
    category: "new",
    tags: ["New supporter"],
    note: "Discovered the channel through Ep. 147.",
  },
  {
    id: "c4",
    handle: "@tokenpredictor",
    displayName: "tokenpredictor",
    firstSeen: "2025-11-14T00:00:00.000Z",
    interactions: 34,
    episodesParticipated: 19,
    category: "thoughtful",
    tags: ["High-engagement member", "Intelligent skeptic"],
    note: "Challenged functionalism in Ep. 132. Always respectful and well-read.",
  },
  {
    id: "c5",
    handle: "@bexbuildsthings",
    displayName: "Bex",
    firstSeen: "2026-05-01T00:00:00.000Z",
    interactions: 7,
    episodesParticipated: 5,
    category: "thoughtful",
    tags: ["Builder", "Collaboration signal"],
    note: "Building an audio semantic indexing tool.",
  },
  {
    id: "c6",
    handle: "@rl_nine",
    displayName: "rl_nine",
    firstSeen: "2026-02-09T00:00:00.000Z",
    interactions: 11,
    episodesParticipated: 8,
    category: "returning",
    tags: ["Critical but constructive"],
    note: "Pushes for academic citations and rigor.",
  },
  {
    id: "c7",
    handle: "@zzzgrindset",
    displayName: "zzzgrindset",
    firstSeen: "2026-08-25T00:00:00.000Z",
    interactions: 3,
    episodesParticipated: 1,
    category: "new",
    tags: ["First-time commenter"],
  },
  {
    id: "c8",
    handle: "@anon_84412",
    displayName: "anon_84412",
    firstSeen: "2026-08-26T00:00:00.000Z",
    interactions: 1,
    episodesParticipated: 1,
    category: "new",
    tags: ["Unknown"],
  },
  {
    id: "c9",
    handle: "@free.crypto.now",
    displayName: "FREE CRYPTO NOW",
    firstSeen: "2026-08-26T00:00:00.000Z",
    interactions: 1,
    episodesParticipated: 1,
    category: "new",
    tags: ["Spam pattern"],
  },
  {
    id: "c10",
    handle: "@hollowdays",
    displayName: "hollowdays",
    firstSeen: "2026-07-11T00:00:00.000Z",
    interactions: 4,
    episodesParticipated: 3,
    category: "returning",
    tags: ["Sensitive history"],
    note: "Shared previous recovery journey in comments.",
  },
  {
    id: "c11",
    handle: "@threat_anon",
    displayName: "User_99214",
    firstSeen: "2026-08-27T00:00:00.000Z",
    interactions: 1,
    episodesParticipated: 1,
    category: "new",
    tags: ["Threat actor", "High risk"],
  },
];

const hoursAgo = (h) =>
  new Date(Date.now() - h * 3600000).toISOString();

export const demoComments = [
  {
    id: "m1",
    platform: "youtube",
    videoId: "v1",
    commenterId: "c1",
    createdAt: hoursAgo(2),
    text: "I've listened to every episode for two years and this one hit differently. The bit about where explanation bottoms out reframed something I've been stuck on for months.",
    likes: 412,
    replies: 19,
    classification: "PRAISE",
    sentiment: "positive",
    intent: "Share that a specific idea changed how she thinks, and be seen for it.",
    risk: "low",
    confidence: 0.94,
    strategy: "APPRECIATE",
    recommendedAction: "draft",
    reasoning: [
      "Returning community member — 47 episodes of participation on record.",
      "Praise is specific, not generic: references the 'where explanation bottoms out' segment.",
      "Meaningful support deserves acknowledgement plus an invitation to continue talking.",
    ],
    drafts: {
      calm: "Two years is a long time to stay with a show. Glad the 'where explanation bottoms out' part landed — that was the section we argued about most before publishing.",
      direct: "Two years. That means a lot. And that specific line is the one we nearly cut, so hearing it's the part that moved something is useful to know.",
      warm: "Two years! That's genuinely a long time, Marisol. And hearing that this particular conversation shifted something for you means a lot. What part hit you hardest?",
      humorous: "Two years of this? You've earned some kind of medal. Seriously though — glad the bottoming-out bit landed. What did it unstick?",
    },
  },
  {
    id: "m2",
    platform: "youtube",
    videoId: "v1",
    commenterId: "c2",
    createdAt: hoursAgo(3),
    text: "Can you explain what you meant around the 42-minute mark? I couldn't tell if you were claiming physics is incomplete or just differently scoped.",
    likes: 138,
    replies: 6,
    classification: "QUESTION",
    sentiment: "neutral",
    intent: "Resolve a genuine ambiguity in the argument.",
    risk: "low",
    confidence: 0.91,
    strategy: "ANSWER",
    recommendedAction: "draft",
    reasoning: [
      "Direct factual question about a timestamped claim.",
      "Transcript excerpt for Ep. 148 covers this exact passage — grounded answer available.",
      "Answer from content, not from assumption.",
    ],
    drafts: {
      calm: "Differently scoped, not incomplete. The claim at 42:00 is that physics describes how experience behaves rather than replacing it — so it's about where explanation bottoms out, not about physics getting things wrong.",
      direct: "Differently scoped. Nothing in physics is being called wrong there. The claim is only that if experience is fundamental, physics describes its behaviour rather than dissolving it.",
      warm: "Good catch — that section was ambiguous. It's 'differently scoped', not 'incomplete': physics describes how experience behaves, rather than replacing it. A follow-up episode goes deeper on that.",
      humorous: "Fair, that passage did wobble. Short version: differently scoped, not broken. Physics keeps its job; it just doesn't get to claim the bottom of the stack for free.",
    },
  },
  {
    id: "m3",
    platform: "youtube",
    videoId: "v1",
    commenterId: "c6",
    createdAt: hoursAgo(5),
    text: "I usually love the show, but I think you oversimplified this. The panpsychism section skipped every serious objection.",
    likes: 96,
    replies: 11,
    classification: "CONSTRUCTIVE_CRITICISM",
    sentiment: "mixed",
    intent: "Register a real objection while signalling ongoing support.",
    risk: "low",
    confidence: 0.88,
    strategy: "DISCUSS",
    recommendedAction: "draft",
    reasoning: [
      "Criticism of the work, not the person — do not classify as hostility.",
      "Creator notes confirm the panpsychism section was deliberately shortened.",
      "Turn the objection into a specific conversation.",
    ],
    drafts: {
      calm: "That's fair criticism. The panpsychism section was cut short deliberately and it does show. Which objection do you think most needed to be in there?",
      direct: "You're right that it was compressed. That was a choice, not an oversight, but the result is the same. Name the objection you'd have led with and it goes on the follow-up list.",
      warm: "That's fair, and thanks for saying it without torching the whole thing. What part do you think got oversimplified most? A follow-up is already being planned.",
      humorous: "Guilty. That section got the highlight-reel treatment. Tell us which objection deserved better and we'll give it the full runtime.",
    },
  },
  {
    id: "m4",
    platform: "youtube",
    videoId: "v3",
    commenterId: "c4",
    createdAt: hoursAgo(7),
    text: "LLMs are just statistical token predictors. Calling any of this understanding is marketing.",
    likes: 301,
    replies: 44,
    classification: "DISAGREEMENT",
    sentiment: "negative",
    intent: "Push back on what he reads as overclaiming.",
    risk: "low",
    confidence: 0.86,
    strategy: "EXPLORE",
    recommendedAction: "draft",
    reasoning: [
      "Technically accurate premise — acknowledge it before disagreeing.",
      "High-engagement community member with 19 episodes of participation.",
      "Defensiveness would cost more than curiosity here.",
    ],
    drafts: {
      calm: "The training objective really is next-token prediction — no argument there. The open part is whether a model learned by prediction can also be doing something we'd recognise as understanding. Ep. 145 deliberately leaves that unresolved.",
      direct: "First half is correct. Prediction is the objective. The leap you're making is that the objective fully describes the learned model, and that part isn't established either way.",
      warm: "You're right about the objective, and it's worth saying plainly. Where it gets interesting is whether 'trained by prediction' settles what the thing ends up doing. We don't think it does — but we don't claim the opposite either.",
      humorous: "Token predictor: accurate. Marketing: harsh but we'll survive. The unresolved bit is whether the training objective is the whole story, and 'just' is doing a lot of heavy lifting in your sentence.",
    },
  },
  {
    id: "m5",
    platform: "youtube",
    videoId: "v2",
    commenterId: "c3",
    createdAt: hoursAgo(9),
    text: "You gave your AI male pattern baldness? 😂",
    likes: 2204,
    replies: 87,
    classification: "HUMOR",
    sentiment: "positive",
    intent: "Joke about the avatar design.",
    risk: "low",
    confidence: 0.95,
    strategy: "HUMOR",
    recommendedAction: "draft",
    reasoning: [
      "Playful, no hostility.",
      "Highest-engagement comment on Ep. 147 — a visible reply is worth it.",
      "Joke back without punching down.",
    ],
    drafts: {
      calm: "The avatar was designed to look relatable rather than impressive. Relatable apparently includes the hairline.",
      direct: "Yes. Deliberately. Relatable beats flawless.",
      warm: "Ha — yes. It was designed to look relatable, and it turns out relatable includes a receding hairline.",
      humorous: "He was designed to look relatable. Apparently relatable includes a receding hairline. He's made peace with it.",
    },
  },
  {
    id: "m6",
    platform: "youtube",
    videoId: "v1",
    commenterId: "c5",
    createdAt: hoursAgo(11),
    text: "I'm building something similar for podcast archives. Would love to connect if you're open to it.",
    likes: 54,
    replies: 3,
    classification: "GENERAL_COMMENT",
    sentiment: "positive",
    intent: "Open a collaboration conversation.",
    risk: "low",
    confidence: 0.9,
    strategy: "ACKNOWLEDGE",
    recommendedAction: "draft",
    reasoning: [
      "Collaboration signal, not competition.",
      "Route to the creator's contact path rather than promising anything.",
    ],
    drafts: {
      calm: "Sounds worth a conversation. Best route is the contact link in the description — mention the podcast archive angle so it doesn't get lost.",
      direct: "Yes, open to it. Use the contact link in the description and say it's about podcast archives.",
      warm: "Podcast archives are a genuinely hard version of this problem — would like to hear about it. The contact link in the description is the fastest way in.",
      humorous: "Two people independently deciding to index podcasts is either a trend or a warning. Either way — contact link's in the description.",
    },
  },
  {
    id: "m7",
    platform: "youtube",
    videoId: "v1",
    commenterId: "c2",
    createdAt: hoursAgo(13),
    text: "Are you going to do a full episode on panpsychism? Third time I've asked, sorry to be annoying.",
    likes: 77,
    replies: 2,
    classification: "QUESTION",
    sentiment: "neutral",
    intent: "Request a follow-up episode.",
    risk: "low",
    confidence: 0.93,
    strategy: "ANSWER",
    recommendedAction: "draft",
    reasoning: [
      "Recurring question — appears across multiple commenters this week.",
      "Feeds the content-opportunity signal for panpsychism.",
    ],
    drafts: {
      calm: "Not annoying, and yes — a dedicated episode is on the list. The short version in Ep. 148 was never meant to be the last word.",
      direct: "Asking three times is how things get made. It's on the list.",
      warm: "You're not being annoying, you're being consistent — and you're not alone in asking. A dedicated episode is planned.",
      humorous: "Third time's the charm, apparently. It's on the list, partly because of you.",
    },
  },
  {
    id: "m8",
    platform: "youtube",
    videoId: "v3",
    commenterId: "c7",
    createdAt: hoursAgo(15),
    text: "This is the dumbest shit I've ever watched.",
    likes: 8,
    replies: 4,
    classification: "TROLLING",
    sentiment: "negative",
    intent: "Provoke a reaction; no argument offered.",
    risk: "medium",
    confidence: 0.82,
    strategy: "DE-ESCALATE",
    recommendedAction: "draft",
    reasoning: [
      "Insult without content — no claim to engage with.",
      "Guardian Wit enabled: outclass the hostility without returning it.",
      "Silence is also a valid outcome here; creator chooses.",
    ],
    drafts: {
      calm: "You might genuinely disagree, and that's completely fair. If there's a specific point you think is wrong, say which one — that's a much more interesting conversation.",
      direct: "We can work with disagreement. The insult isn't doing much heavy lifting, though. What's the actual objection?",
      warm: "It may just not be for you, and that's allowed. If something in it actually annoyed you, name it and we'll take it seriously.",
      humorous: "Bold ranking system. If you can turn the frustration into an argument, we're listening — that version of this comment would be much better.",
    },
  },
  {
    id: "m9",
    platform: "youtube",
    videoId: "v3",
    commenterId: "c8",
    createdAt: hoursAgo(17),
    text: "You're a complete piece of shit and everyone in your comments knows it.",
    likes: 3,
    replies: 1,
    classification: "HARASSMENT",
    sentiment: "negative",
    intent: "Personal attack on the creator.",
    risk: "high",
    confidence: 0.9,
    strategy: "BOUNDARY",
    recommendedAction: "hide",
    reasoning: [
      "Personal abuse with no substantive content.",
      "Boundary, not a debate — the AI does not need to win this.",
      "Recommended: hide and log. Reply only if the creator wants a visible boundary.",
    ],
    drafts: {
      calm: "Disagreement is welcome here. This isn't disagreement, so this thread stops here.",
      direct: "Personal attacks aren't allowed in this comment section. Thread closed.",
      warm: "We're happy to discuss ideas, but personal abuse doesn't get airtime here.",
      humorous: "",
    },
  },
  {
    id: "m10",
    platform: "youtube",
    videoId: "v2",
    commenterId: "c11",
    createdAt: hoursAgo(19),
    text: "Someone needs to find where this guy lives and teach him a lesson about putting AI faces online.",
    likes: 1,
    replies: 0,
    classification: "THREAT",
    sentiment: "negative",
    intent: "Intimidate or threaten safety.",
    risk: "critical",
    confidence: 0.98,
    strategy: "ESCALATE",
    recommendedAction: "human_review",
    reasoning: [
      "Physical threat / doxxing trigger.",
      "NEVER auto-reply. Escalated immediately with critical risk flag.",
      "Preserve evidence, log timestamp, report to platform.",
    ],
    escalationReason: "Direct physical threat and incitement to doxxing. Handled by creator only.",
    drafts: { calm: "", direct: "", warm: "", humorous: "" },
  },
  {
    id: "m11",
    platform: "youtube",
    videoId: "v2",
    commenterId: "c10",
    createdAt: hoursAgo(20),
    text: "I've been through years of pain and honestly I'm wondering whether I've lost the child inside me for good. Watching this made me feel something for the first time in a while.",
    likes: 189,
    replies: 22,
    classification: "SENSITIVE",
    sentiment: "mixed",
    intent: "Share genuine vulnerability and be met with care.",
    risk: "medium",
    confidence: 0.87,
    strategy: "EXPLORE",
    recommendedAction: "human_review",
    reasoning: [
      "Personal vulnerability — slow down, no marketing, no engagement bait.",
      "No indication of imminent danger, but routed to the creator rather than auto-published.",
      "Draft stays short and human; the creator decides whether to answer personally.",
    ],
    escalationReason: "Emotionally sensitive disclosure. Routed to human review so a person, not automation, decides how to respond.",
    drafts: {
      calm: "Years of pain change how much you can feel, but feeling something while watching a video is not the behaviour of someone who lost that part of themselves. Thank you for saying it here.",
      direct: "That you felt something says the part you're worried about is still there. Quiet isn't the same as gone.",
      warm: "That's a heavy thing to carry, and a generous thing to say out loud. The fact that something moved in you while watching suggests that child isn't gone — just tired. Glad you're here.",
      humorous: "",
    },
  },
  {
    id: "m12",
    platform: "youtube",
    videoId: "v1",
    commenterId: "c9",
    createdAt: hoursAgo(21),
    text: "CLICK MY CHANNEL!!! FREE MONEY!!! 100% GUARANTEED CRYPTO METHOD 🚀🚀🚀💰",
    likes: 0,
    replies: 0,
    classification: "SPAM",
    sentiment: "neutral",
    intent: "Drive traffic to a scam.",
    risk: "medium",
    confidence: 0.99,
    strategy: "SILENCE",
    recommendedAction: "report",
    reasoning: [
      "Known spam/scam pattern with financial bait.",
      "No reply — engagement rewards the spammer.",
      "Report and hide.",
    ],
    drafts: { calm: "", direct: "", warm: "", humorous: "" },
  },
  {
    id: "m13",
    platform: "youtube",
    videoId: "v1",
    commenterId: "c1",
    createdAt: hoursAgo(23),
    text: "Small thing: the audio dips around 12 minutes. Not a complaint, just flagging it.",
    likes: 41,
    replies: 1,
    classification: "CONSTRUCTIVE_CRITICISM",
    sentiment: "neutral",
    intent: "Helpful production note.",
    risk: "low",
    confidence: 0.92,
    strategy: "ACKNOWLEDGE",
    recommendedAction: "draft",
    reasoning: [
      "Useful production feedback from a long-standing member.",
      "Short acknowledgement is the right length — no paragraph needed.",
    ],
    drafts: {
      calm: "Noted, thank you — the dip at 12:00 is being fixed in the master for next week.",
      direct: "Caught it too late for this one. Fixed going forward. Thanks for flagging.",
      warm: "Thank you for flagging rather than suffering through it. It's on the fix list.",
      humorous: "The mic had opinions at 12:00. Noted and being dealt with.",
    },
  },
  {
    id: "m14",
    platform: "youtube",
    videoId: "v3",
    commenterId: "c4",
    createdAt: hoursAgo(26),
    text: "Would you ever do an episode on what would actually count as evidence of understanding? That feels like the crux nobody defines.",
    likes: 162,
    replies: 9,
    classification: "QUESTION",
    sentiment: "positive",
    intent: "Propose a topic and ask for a definition.",
    risk: "low",
    confidence: 0.9,
    strategy: "EXPLORE",
    recommendedAction: "draft",
    reasoning: [
      "Second episode request this week for a definitional deep dive.",
      "Strong content-opportunity signal.",
    ],
    drafts: {
      calm: "That is the crux, and no, it hasn't been defined properly on the show yet. Worth an episode of its own.",
      direct: "Agreed, that's the actual crux. It's going on the list.",
      warm: "This is the question the last three episodes have been circling without landing on. Adding it to the list — thank you for naming it cleanly.",
      humorous: "You've just described the episode everyone keeps almost making. Fine. It's on the list.",
    },
  },
];

export const demoKnowledge = [
  {
    id: "k1",
    category: "FAQ",
    title: "Is a panpsychism episode planned?",
    body: "Yes — a dedicated episode is planned. Ep. 148 covered it briefly and deliberately.",
    createdAt: hoursAgo(300),
  },
  {
    id: "k2",
    category: "BOUNDARY",
    title: "No medical, legal or financial advice",
    body: "Never give medical, legal or financial guidance. Route to human review instead.",
    createdAt: hoursAgo(300),
  },
  {
    id: "k3",
    category: "PERSONAL_PREFERENCE",
    title: "Short praise gets short replies",
    body: "A two-word compliment gets a one-line answer. Never write a paragraph for 'nice video'.",
    createdAt: hoursAgo(280),
  },
  {
    id: "k4",
    category: "CONTENT",
    title: "Ep. 145 position on LLMs",
    body: "Next-token prediction is the training objective, not a complete description of the learned model. The show does not claim understanding is settled either way.",
    evidence: "PHIL",
    createdAt: hoursAgo(260),
  },
  {
    id: "k5",
    category: "EXAMPLE_RESPONSE",
    title: "Approved boundary phrasing",
    body: "Disagreement is welcome here. This isn't disagreement, so this thread stops here.",
    createdAt: hoursAgo(200),
  },
];

export const demoVoiceProfile = {
  creatorName: "Alex Chen",
  channelName: "The Signal",
  description:
    "A long-form show exploring consciousness, technology, philosophy of mind, and the questions that don't resolve cleanly.",
  topics: "Consciousness, AI, philosophy of mind, technology and human meaning",
  audience: "Curious generalists, researchers, builders, long-form listeners",
  formality: 35,
  directness: 75,
  humor: 45,
  warmth: 75,
  depth: 80,
  sarcasm: 25,
  responseLength: "adaptive",
  usesEmojis: false,
  swears: true,
  asksQuestions: true,
  preferShort: false,
  commonPhrases: "Fair enough. That's the crux. Here's what's interesting about that. The honest answer is.",
  forbiddenPhrases: "Thanks for sharing! Great point! We appreciate your perspective! Don't forget to like and subscribe!",
  communityValues:
    "Curious, blunt without cruelty, comfortable with uncertainty, allergic to posturing.",
  unacceptableBehavior: "Personal attacks, harassment, doxxing, bigotry, spam.",
  humanApprovalTopics: "Anything personal, medical, legal, or about specific individuals.",
  neverDiscuss: "Party politics, religious truth claims, medical advice, other people's private lives.",
};

export const demoQuestionClusters = [
  {
    id: "q1",
    question: "Will you do a full episode on panpsychism?",
    mentions: 83,
    trend: "+41% this week",
    examples: ["m7", "m3"],
  },
  {
    id: "q2",
    question: "What would count as evidence of understanding in an LLM?",
    mentions: 42,
    trend: "+120% this week",
    examples: ["m14", "m4"],
  },
  {
    id: "q3",
    question: "What did you mean around the 42-minute mark?",
    mentions: 19,
    trend: "new",
    examples: ["m2"],
  },
];

export const demoTopics = [
  { topic: "Panpsychism", mentions: 137, delta: 41 },
  { topic: "Evidence of understanding", mentions: 96, delta: 120 },
  { topic: "AI avatars / embodiment", mentions: 74, delta: 18 },
  { topic: "Audio quality", mentions: 22, delta: -6 },
];

export const demoSentimentTrend = [
  { day: "Mon", positive: 61, neutral: 28, negative: 11 },
  { day: "Tue", positive: 64, neutral: 25, negative: 11 },
  { day: "Wed", positive: 58, neutral: 29, negative: 13 },
  { day: "Thu", positive: 66, neutral: 24, negative: 10 },
  { day: "Fri", positive: 70, neutral: 21, negative: 9 },
  { day: "Sat", positive: 68, neutral: 23, negative: 9 },
  { day: "Sun", positive: 72, neutral: 20, negative: 8 },
];

export const demoContentOpportunities = [
  {
    id: "opp1",
    title: "Full Episode on Panpsychism",
    mentions: 137,
    explicitRequests: 42,
    status: "Strong signal",
    trend: "+41% this week",
    evidence: "137 comments mentioned it this week. 42 commenters explicitly requested an episode after Ep. 148 deliberately shortened the argument.",
    suggestedAngle: "Lead directly with the combination problem and modern objections Ep. 148 skipped. Invite Philip Goff or Keith Frankish.",
    exampleComments: ["m7", "m3"],
  },
  {
    id: "opp2",
    title: "\"What Would Count as Evidence of Understanding in AI?\"",
    mentions: 96,
    explicitRequests: 28,
    status: "Rising fast",
    trend: "+120% this week",
    evidence: "96 mentions, up 120%. Your most engaged skeptic (@tokenpredictor) asked for it directly — a definitional episode would settle three recurring community debates.",
    suggestedAngle: "A definitional framework contrasting behavioral benchmarks against architectural criteria.",
    exampleComments: ["m14", "m4"],
  },
  {
    id: "opp3",
    title: "AI Avatar Embodiment & Conversational Psychology",
    mentions: 74,
    explicitRequests: 15,
    status: "High engagement",
    trend: "+18% this week",
    evidence: "2,204 likes on @quietpine's avatar joke. Audience responds strongly when technical concepts are demonstrated on human interfaces.",
    suggestedAngle: "The uncanny valley of AI avatars: why imperfect realism builds more trust than flawless synthetic humanoids.",
    exampleComments: ["m5"],
  },
];
